FLOW_HOME := /home/quxiaolei/work/ysyx/yosys-sta
DESIGN_HOME := $(CURDIR)

# 你的顶层模块名，自己改
DESIGN := top

# 你的 RTL 和 SDC 路径，按你项目实际目录改
RTL_DIR := $(DESIGN_HOME)/rtl
SDC_FILE := $(DESIGN_HOME)/constraint/default.sdc

include $(FLOW_HOME)/Makefile